---
- hosts: webservers
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: install PHP repository
    apt_repository:
        repo: ppa:ondrej/php

  - name: Update apt-get repo and cache
    apt: update_cache=yes

  - name: install PHP packages
    apt:
      pkg:
        - git
        - mcrypt
        - nginx
        - php7.3
        - php7.3-fpm
        - php7.3-cli
        - php7.3-curl
        - php7.3-intl
        - php7.3-json
      state: present