---
- hosts: webservers
  become: true

  tasks:

  - name: install PHP repository
    apt_repository:
        repo: ppa:ondrej/php
    become: true    

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - mcrypt
      - nginx
      - php7.3
      - php7.3-cli
      - php7.3-curl
      - php7.3-fpm
      - php7.3-intl
      - php7.3-json
      - php7.3-mcrypt