##################################################
# DO Community Playbooks: LEMP on Ubuntu 18.04
##################################################
---
- hosts: dbservers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/default.yml

  tasks:
    - name: installing MySQL server on server
      apt: pkg={{item}} update_cache=yes cache_valid_time=86400 state=present
      with_items:
      - python-mysqldb
      - mysql-server

    - name: Start mysql service
      service: name=mysql state=started

    - name: configuring root user pass and priveliges
      mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} priv=*.*:ALL,GRANT
      with_items:
      - "{{ inventory_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost