##################################################
# DO Community Playbooks: LEMP on Ubuntu 18.04
##################################################
---
- hosts: dbservers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/default.yml

  tasks:

    - name: install PHP repository
      apt_repository:
        repo: ppa:ondrej/php

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude', 'nginx', 'python3-pip', 'libmysqlclient-dev', 'php7.3', 'php7.3-fpm']

    # PIP Module  
    - name: Install PIP Module
      sudo: yes
      pip:
        name: "{{ item }}"
        state: forcereinstall
      with_items:
        - mysqlclient

    - name: Install DB Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mysql-server','phpmyadmin', 'php7.3-mbstring', 'php7.3-gettext', 'php7.3-mysqli']  
    
    - name: Copy nginx default phpmyadmin
      template:
        src: "files/default.j2"
        dest: "/etc/nginx/sites-available/default"

    - name: Start php-fpm
      service:
        name: "php{{phpfpm_version}}-fpm"
        state: "started" 

    - name: Start nginx
      service:
        name: "nginx"
        state: "started" 

    # MySQL Configuration
    - name: Start MySQL
      service:
        name: "mysql"
        state: "started"
        enabled: "yes"
      become: "yes"
              
    - name: Sets the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"  

    - name: Sets the phpmyadmin password
      mysql_user:
        name: phpmyadmin
        password: "{{ mysql_root_password }}"
        priv: '*.*:ALL'

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"    
    
    - name: Removes the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"    

    - name: Create database user billing
      mysql_user:
        name: billing
        password: "{{ mysql_billing_password }}"
        priv: '*.*:ALL'
        state: present    